apiVersion: apps/v1
kind: Deployment
metadata:
  name: endo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: endo-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: endo-app
    spec:
      containers:
      - name: endo-app
        image: endo-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: endo-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: endo-app